### ISSUE TITLE
Possible improvement with spanish vs french

### ISSUE THREAD

**Issue by jcornide** [patrickschur/language-detection#10]
Hi,

I started using this library and it works great most of the time but I came across a problem with the following sentence in spanish: "Este es un mensaje de prueba"
That results in the following scores:
[fr] => 0.56424275560416
[es] => 0.54543466375068
[pt-PT] => 0.52006560962274
[pt-BR] => 0.51919081465282

Spanish should be the first one, I know that maybe its a very short text but maybe you can improve something here.

Cheers

**Comment by patrickschur** [comment]
I'm glad you like it. The library is more or less optimized on speed. If you want to get better results you have to set the max amount of ngrams to something greater than 300.
Here an example of how you can reach this:
```php
// First of we have to "train" our program
// Execute this small script (it will take 1-2 seconds)
// After executing you can delete this file or this three lines
$tr = new \LanguageDetection\Trainer();
$tr->setMaxNgrams(1000); // set maxNgrams to 1000
$tr->learn();
```
Now if you want to get better results you have to specify the max amount of ngrams you are using:
```php
$ld = new LanguageDetection\Language(['fr', 'es', 'pt-PT', 'pt-BR']);
// set the max amount of ngrams using setMaxNgrams
$ld->setMaxNgrams(1000); // default 300, we will use 1000 (the same value as above)

print_r($ld->detect('Este es un mensaje de prueba'));
```
This gives me the following results:
```txt
[es] => 0.75047457627119
[fr] => 0.68354237288136
[pt-BR] => 0.68230508474576
[pt-PT] => 0.67372881355932
```

**Comment by jcornide** [comment]
Thanks a lot!
