### ISSUE TITLE
__toString() must be of the type string, null returned

### ISSUE THREAD

**Issue by i951143114** [patrickschur/language-detection#11]
PHP 7.0 + Laravel 5.5

`$language = $this->languageDetect->detect($rankedKeyword->query)->__toString();`

[2017-09-22 15:40:33] local.ERROR: Type error: Return value of LanguageDetection\LanguageResult::__toString() must be of the type string, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of LanguageDetection\\LanguageResult::__toString() must be of the type string, null returned at /var/www/html/meek.com.cn/trendx-crawler/vendor/patrickschur/language-detection/src/LanguageDetection/LanguageResult.php:86)
[stacktrace]
#0 /var/www/html/meek.com.cn/trendx-crawler/app/GoogleTrendsCrawler.php(212): LanguageDetection\\LanguageResult->__toString()
#1 /var/www/html/meek.com.cn/trendx-crawler/app/Console/Commands/Crawl.php(53): App\\GoogleTrendsCrawler->fetchQueries(Array)
#2 [internal function]: App\\Console\\Commands\\Crawl->handle()
#3 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#8 /var/www/html/meek.com.cn/trendx-crawler/vendor/symfony/console/Command/Command.php(264): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/www/html/meek.com.cn/trendx-crawler/vendor/symfony/console/Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/www/html/meek.com.cn/trendx-crawler/vendor/symfony/console/Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\Crawl), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/www/html/meek.com.cn/trendx-crawler/vendor/symfony/console/Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/html/meek.com.cn/trendx-crawler/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/html/meek.com.cn/trendx-crawler/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"}

**Comment by patrickschur** [comment]
Your `$rankedKeyword->query` is empty or only contains characters that are not supported, like punctuation. 
To prevent this behaviour you have to check the array of emptiness or use the JSON output.
```php
$obj = $ld->detect('This is an example!');

if (!empty($obj->close()))
{
    echo $obj; // $obj->__toString();
}
```
Maybe I should throw an exception or check for null in the result?

**Comment by i951143114** [comment]
Thank you!
