### ISSUE TITLE
TypeError: Return value of LanguageDetection\LanguageResult::__toString() must be of the type string, null returned

### ISSUE THREAD

**Issue by tuanpt216** [patrickschur/language-detection#13]
Error caused in https://github.com/patrickschur/language-detection/blob/master/src/LanguageDetection/LanguageResult.php#L86
```php
    /**
     * @return string
     */
    public function __toString(): string
    {
        return key($this->result);
    }
```
Function `key()` return null with an empty array.

An example case is when language input is number, e.g. `echo (string) $ld->detect('1992');`

I will send pull request if you need.
Thank you.

**Comment by patrickschur** [comment]
> I will send pull request if you need.

Sure if you already have one. :)
You are welcome to contribute to this project.

Thanks for your help.

**Comment by tuanpht** [comment]
Sorry, this is duplicated with issue #11, I didn't check for it first.
But I think, that function `__toString()` should not raise an exception, I've created pull request #14.
