### ISSUE TITLE
__toString() must be of the type string, null returned

### ISSUE THREAD

**Issue by nachitox** [patrickschur/language-detection#18]
When there's no results, `__toString()` returns null which conflicts with the return type.
Happens when the input string is empty (maybe some other cases)

**Comment by patrickschur** [comment]
Which version do you use? Because this issue was already addressed and (fixed?) in a previous [issue](https://github.com/patrickschur/language-detection/issues/13).

**Comment by nachitox** [comment]
I did `composer require patrickschur/language-detection` so, that one :P 
`composer show` says it's v3.2.0

**Comment by patrickschur** [comment]
Looks like the actual version doesn't include the fix. I will update the version for you. :)
