### ISSUE TITLE
dk is not a valid language code

### ISSUE THREAD

**Issue by bbalet** [patrickschur/language-detection#19]
Please see: http://www.loc.gov/standards/iso639-2/php/code_list.php
I think you confused with the country code:
 * da is the language code for Danish
 * da-DK is the regional Danish language spoken in Danemark

**Comment by patrickschur** [comment]
You're right. I'll change that as soon as I have time.
Thanks!

**Comment by patrickschur** [comment]
@bbalet I've fixed the issue. I'm sorry that it took so long. :( Thanks for you support. :)
