### ISSUE TITLE
Grille pain question 4

### ISSUE THREAD

**Issue by michelollivier** [patrickschur/language-detection#2]
Hi,

Sorry, I forgot question 4:

'xzy' returns

```
array(6) {
  ["it"]=>
  float(0.092666666666667)
  ["en"]=>
  float(0.092)
  ["nl"]=>
  float(0.088)
  ["de"]=>
  float(0.084666666666667)
  ["es"]=>
  float(0.081666666666667)
  ["fr"]=>
  float(0.043333333333333)
}
```

I can not launch translation with that.

-Could your briefly explain what this figures are and at which level one can say that they are reliable enough to return a detected language. You could add a bestResult() method 'winner by KO' (like germany brasil 7-0 ;).

-Maybe more interesting for developers, would be to add a validate() method  which returns false if we definitely can not detect. I will insert it in my validation process.

Thanks again.
Michel

**Comment by patrickschur** [comment]
Germany vs Brazil was 7-1 :smile: 
You don't have to create a new issue for that. (Next time, please add your question under your previous comment. I mean it well.)

1) It's a language detector not a word detector. It tries to find out in which language a given word is written. The given word for example `xyz` will decomposed into N-grams: (The underscore means the beginning or end of the word)
```text
Array
(
    [0] => xyz
    [1] => _xy
    [2] => yz_
    [3] => _x
    [4] => xy
    [5] => yz
    [6] => z_
    [7] => x
    [8] => y
    [9] => z
)
```
Now the first 10 elements of each language file are compared against the N-grams. The language that comes closest to the result gets a higher rating. That is the whole magic.

There is already a bestResult() method. :+1: Can you explain that?

2) This is a good idea but difficult to implement, see my first point. I'll try to do this. But I can not promise anything.

What exactly are you doing with it? :smiley:

**Comment by michelollivier** [comment]
Hi,

I am french.

I translate my website on the fly plus every text that user can send through forms. To avoid slow loading, I store each translations into a database. First translation is done through yandex api, following through database. Moreover, I have to validate user text to check if his/her text is well in my language selection list (it's coupled with a bad words checker).

Everything start with a language detection. It has to be fast and reliable. Yandex allows language detection but it's not fast enough, google also, as every api. 

So, my real issue is that my users enter short sentences or single words, and I dont want to build a huge multilanguage dictionnary for small words...

Or I find a pretty sure language detector for single word / small sentence, or I find a dictionnary base.

Hard time.

Regards
Michel

**Comment by patrickschur** [comment]
Hi,
the biggest problem is, there is no way to properly recognize the language. At least not for single words.
Here's an example: The word `skateboard` which languages is that? English, German, Dansk or Itlian? I Hope you understand what I mean.

I can understand you, a dictionary also does not represent a good solution.
If you have a look at my repository [dict](https://github.com/patrickschur/dict) you can see that alone the German language has more than 200.000 words (2.33 MB).

Can you tell me how fast is my script in relation to others? :smile: 
Is there anything else you want?

**Comment by michelollivier** [comment]
So I have to accept a certain level of uncertainty in language detection and do a human check on language database from time to time. Thanks for your help.
Regards
Michel

**Comment by patrickschur** [comment]
You didn't answer my question, but you are welcome. :smiley:
