### ISSUE TITLE
Get language name by language code

### ISSUE THREAD

**Issue by 4n70w4** [patrickschur/language-detection#21]
I suggest an improvement. Return not only the language code, but also its name.
 
https://github.com/patrickschur/language-detection/blob/master/resources/README.md

**Comment by patrickschur** [comment]
Can you give me an example where this would be helpful? I mean why do you need the language name if you already have the language code?

**Comment by 4n70w4** [comment]
@patrickschur for example, display the language name on the screen.

**Comment by patrickschur** [comment]
Implementing such a feature needs major changes on the code base. And also remember this library is not only for detecting languages. So I see some problems implementing this feature. 
If you need this feature, I would suggest you to use a map or something like that.

```php
$languageNames = [
    'en' => 'English',
    'es' => 'Spanish',
    // [...]
];
```

**Comment by 4n70w4** [comment]
@patrickschur but this list will not be synchronized with the list of languages of your library.

**Comment by tpetry** [comment]
Translations for language keys is available in php core: [locale_get_display_language](http://php.net/manual/de/locale.getdisplaylanguage.php)

**Comment by 4n70w4** [comment]
@tpetry thanks, it is right for me. The issue is resolved.
