### ISSUE TITLE
Trainer echo?

### ISSUE THREAD

**Issue by FLasH3r** [patrickschur/language-detection#22]
Hi,

I'm using the Trainer class like so:

```php
$languageTrainer = new Trainer();
$languageTrainer->setMaxNgrams(9000);
$languageTrainer->learn();
```
I wasn't expecting it to echo anything - why is it not returning a success / failure? 

![image](https://user-images.githubusercontent.com/1413249/54638887-bb547380-4a94-11e9-9d22-23b23b2a88b2.png)

Also, GlobIterator expects 2 parameters, 1 given.

![image](https://user-images.githubusercontent.com/1413249/54639038-19815680-4a95-11e9-8fbc-04d769047a8e.png)

**Comment by patrickschur** [comment]
You are right, the method should not echo anything. I will change this by time.
But GlobalIterator does not expect 2 parameters, the second parameter is [optional](http://php.net/manual/de/globiterator.construct.php).
