### ISSUE TITLE
Not correct detect Japanese

### ISSUE THREAD

**Issue by StagnantIce** [patrickschur/language-detection#23]
$ld = new Language(['ja']);
$ld->setMaxNgrams(9000);

var_dump($ld->detect('タイトティーンアクション'));

All results is null, but language is Japanese

**Comment by StagnantIce** [comment]
better solution for me

function isJapanese($lang) {
    return preg_match('/[\x{4E00}-\x{9FBF}\x{3040}-\x{309F}\x{30A0}-\x{30FF}]/u', $lang);
}

**Comment by patrickschur** [comment]
The language detector doesn't know any of these characters. You have to train the language detector to detect your desired sentences. I'm not able to train the language detector on each word for all language that exists. Especially your sentence is very special...
