### ISSUE TITLE
Source of language datasets

### ISSUE THREAD

**Issue by DonaldTsang** [patrickschur/language-detection#26]
Where is the source text dataset for the Ngrams of those 110 languages? Would like to see if it is different from https://github.com/wooorm/franc/issues/78 usage of UDHR, and if it is more accurate than them.

**Comment by patrickschur** [comment]
All language files are based on the official [UDHR](https://www.unicode.org/udhr/downloads.html). Other than franc, I'm using 1-gram, 2-gram and 3-gram sequences and not only 3-gram sequences. Also it's very easy to add your own language files. You can also change the amount of n-grams. 

But I've never tested the accuracy against other libraries, but feel free to do so. :)

**Comment by DonaldTsang** [comment]
Thanks for the notice, unfortunately I am trying to discover new datasets since UDHR is too short, and is overused in many language detection projects.
