### ISSUE TITLE
How can the library detect the wrong language on such simple text?

### ISSUE THREAD

**Issue by nirsharony** [patrickschur/language-detection#33]
I tried the library on the following sentence: "Please delete my account."
The identified languages that i got are listed below.
English came in 5th! 

BTW, I tried this with quite a few English sentences, and the results were not very good...

Am i using the library wrong?
This is what I did:
```
<?php
$detector = new LanguageDetection\Language();
var_export($detector->detect("Please delete my account.")->close());
?>
```

array (
  'fr' => 0.50662139219015,
  'es' => 0.50311262026033,
  'ca' => 0.49643463497453,
  'ro' => 0.48630447085456,
  'en' => 0.48381437464629,
  'ia' => 0.47747594793435,
  'gl' => 0.46955291454443,
  'wa' => 0.46768534238823,
  'nb' => 0.45551782682513,
  'it' => 0.45297113752122,
  'ch' => 0.44923599320883,
  'pt-PT' => 0.44069043576684,
  'da' => 0.44063384267119,
  'pt-BR' => 0.43848330503679,
  'fy' => 0.43746462931522,
  'nn' => 0.43497453310696,
  'af' => 0.4343520090549,
  'br' => 0.43033389926429,
  'sv' => 0.42959818902094,
  'ga' => 0.42716468590832,
  'eo' => 0.42648556876061,
  'la' => 0.4258064516129,
  'io' => 0.42354272778721,
  'de' => 0.42195812110922,
  'et' => 0.42167515563101,
  'hu' => 0.41680814940577,
  'gn' => 0.41533672891907,
  'to' => 0.41041312959819,
  'id' => 0.41001697792869,
  'tr' => 0.40288624787776,
  'cy' => 0.39711375212224,
  'ss' => 0.39400113186191,
  'ug-Latn' => 0.39383135257499,
  'gd' => 0.3933220147142,
  'nl' => 0.39286926994907,
  'ms-Latn' => 0.38828522920204,
  'ku' => 0.38760611205433,
  'sq' => 0.38664402942841,
  'eu' => 0.38075834748161,
  'cs' => 0.37826825127334,
  'fi' => 0.37549518958687,
  'wo' => 0.37006225240521,
  'bi' => 0.36949632144878,
  'xh' => 0.35529145444256,
  'ln' => 0.35466893039049,
  'sl' => 0.35336728919072,
  'jv' => 0.35217883418223,
  'sk' => 0.34821731748727,
  've' => 0.33938879456706,
  'ng' => 0.32823995472552,
  'ig' => 0.32591963780419,
  'pl' => 0.32382569326542,
  'mt' => 0.32252405206565,
  'co' => 0.32116581777023,
  'lv' => 0.3184493491794,
  'lt' => 0.31839275608376,
  'sr-Latn' => 0.31618562535371,
  'lg' => 0.31601584606678,
  'tl' => 0.31494057724958,
  'so' => 0.31290322580645,
  'bs-Latn' => 0.30820599886814,
  'hr' => 0.29881154499151,
  'fj' => 0.29626485568761,
  'ay' => 0.29111488398415,
  'vi' => 0.28726655348048,
  'az-Latn' => 0.28053197509904,
  'kr' => 0.27549518958687,
  'is' => 0.27464629315224,
  'fo' => 0.26779852857951,
  'yo' => 0.26445953593662,
  'ha' => 0.26225240520656,
  'mh' => 0.26140350877193,
  'ty' => 0.22948500282965,
  'nv' => 0.21522354272779,
  'zh-Hans' => 0,
  'sr-Cyrl' => 0,
  'uz' => 0,
  'ur' => 0,
  'uk' => 0,
  'ug-Arab' => 0,
  'ta' => 0,
  'th' => 0,
  'tt' => 0,
  'ab' => 0,
  'sa' => 0,
  'el-polyton' => 0,
  'am' => 0,
  'ar' => 0,
  'az-Cyrl' => 0,
  'be' => 0,
  'bg' => 0,
  'bn' => 0,
  'bo' => 0,
  'bs-Cyrl' => 0,
  'cr' => 0,
  'dz' => 0,
  'el-monoton' => 0,
  'fa' => 0,
  'ru' => 0,
  'gu' => 0,
  'he' => 0,
  'hi' => 0,
  'hy' => 0,
  'iu' => 0,
  'ja' => 0,
  'ka' => 0,
  'km' => 0,
  'ko' => 0,
  'lo' => 0,
  'mn-Cyrl' => 0,
  'ms-Arab' => 0,
  'zh-Hant' => 0,
)

**Comment by patrickschur** [comment]
The library was initially optimized on speed. That's why we only use 320 n-grams for comparison. If you want to improve the results you have to train the library with around 9000 n-grams first. 

After you trained the library with your specified number of n-grams, you can use the library this way.
```
<?php
$detector = new LanguageDetection\Language();
$detector->setMaxNgrams(9000);
var_dump($detector->detect("Please delete my account.")->close());
```

My results:
```
["en"]=>
float(0.88903898635478)
["ca"]=>
float(0.81949122807018)
["ia"]=>
float(0.81797076023392)
["ro"]=>
float(0.81117348927875)
["fy"]=>
float(0.81021247563353)
```
