### ISSUE TITLE
The detected languages seem wrong very often

### ISSUE THREAD

**Issue by nirsharony** [patrickschur/language-detection#38]
Hi.

I am trying out this library and it seems that I am getting wrong language detections.
After training the library with 9.000 n-grams, I tested this code:

```
use LanguageDetection\Language;

$ld = new Language;
$ld->setMaxNgrams(9000);

var_export($ld->detect('Je souhaite annuler mon abonnement')->limit(0, 3)->close());
var_export($ld->detect('Merci beaucoup')->limit(0, 3)->close());
```
I was expecting both sentences to be detected with French at number 1, but I got this:
```
array (
  'fr' => 0.83144592592593,
  'de' => 0.81363111111111,
  'en' => 0.80018962962963,
);
array (
  'en' => 0.8102134502924,
  'fr' => 0.80741520467836,
  'ca' => 0.78646198830409,
);
```
Note how in the second call, French is number 2 and English is number 1.
What is causing this and how can the system be improved to get better results?

Thanks in advance

**Comment by patrickschur** [comment]
The library uses N-grams to recognize a given language and this method doesn't work very well for short sentences like in your second example.

**Comment by vesper8** [comment]
In the example of `Merci beaucoup`, neither of these words are even in the english dictionary so it's difficult to understand how it could guess that this language is english. I'm also seeing this happen a lot with short sentences.. a lot of short english sentences are being guessed as being Spanish, Italian, etc

Is there a way to work around this limitation for this library? Did you figure something out @nirsharony ?
