### ISSUE TITLE
English text recognition

### ISSUE THREAD

**Issue by emresaracoglu** [patrickschur/language-detection#41]
Hello,

This text is in English but I get this as a result.

> xray no change + moderate non irradating pain nxray no change + dull pain nxray no change + biting

`
{
 "ug-Latn": 0.422791679228218253427939998800866305828094482421875,
 "ch": 0.42007838408200182112040010906639508903026580810546875, 
"en": 0.412933373530298464260113178170286118984222412109375, 
"tl": 0.40669279469400054782823872301378287374973297119140625 
}
`

Script states that the text is in Chinese before English.
What is the reason of this?

**Comment by patrickschur** [comment]
The library uses 310 ngrams by default, which is a compromise between speed and accuracy. If you want to improve the detection phase you have to use more ngrams which is also explained in the FAQ.

https://github.com/patrickschur/language-detection#how-can-i-improve-the-detection-phase

Here are my results by using max. 9000 ngrams.

```json
{
  "en":0.8272876427829698,
  "ch":0.7804610591900312,
  "ia":0.7617632398753894,
  "fr":0.7582056074766355
}
```

BTW `ch` is Chamorro and not Chinese. Here is a list with [supported languages](https://github.com/patrickschur/language-detection/tree/master/resources#overview-of-all-supported-languages).

**Comment by emresaracoglu** [comment]
Thank you for your help!

cc @patrickschur
