### ISSUE TITLE
What's the right way of checking whether or not the text is in a specific language?

### ISSUE THREAD

**Issue by marcellofuschi** [patrickschur/language-detection#46]
Hi! I'd like to use this library to check whether or not a (plain) text is in English.

What I'd like to do is something like:
```
if ((new LanguageDetector(['en']))->detect($str)->close()['en'] < THRESHOLD)
  echo 'It surely is not in English';
```

It seems to me that the returned score isn't a probability, though, because it changes based on the `maxNgrams` used (and sometimes is negative). This makes me think that the "threshold" solution above may not be valid.

I might be able to find the answer on my own by digging a bit more into the code but I thought that an answer from the contributors could benefit other users too. Plus, it would be good to add an explanation about what the scores are in the README.

**Comment by patrickschur** [comment]
The library computes the similarity of the N-grams of your input text with the N-grams of the language files. So if your input text has the exact same N-grams (and the order is also the same) as in one of the language files, you should get a score of `1`. If none of the N-grams is found in one of the language files, you should get a `0`. 

If you get a negative score, you probably forgot to train the library and the number of `maxNgrams` is not the same as the number used during training. If this is not the case then something is wrong in the implementation.

**Comment by marcellofuschi** [comment]
Thank you so much for the clear explanation!
