### ISSUE TITLE
What dataset?

### ISSUE THREAD

**Issue by fabiospampinato** [patrickschur/language-detection#51]
Hello there, may I ask what database has been used to create this library?

**Comment by fabiospampinato** [comment]
I guess the answer was here: https://github.com/patrickschur/language-detection/blob/master/resources/README.md

Closing.

**Comment by xmontero** [comment]
If all the training sets are the Unites Nations declaration of Human Rights, then I wonder:

Does not this bias a bit the training? For example the words "article" or "whereas" in English as well as "article" and "considerant" in Catalan appear many more times than they would appear in a regular speaking. Particularly "article" appears 30 times in a single text, which is not normal.

I wonder if this repetition in the training set that does not occur in natural langua biases the proper detection.
