### ISSUE TITLE
Fatal error when trying to detect emoji only string

### ISSUE THREAD

**Issue by arsonik** [patrickschur/language-detection#6]
Failing at : https://github.com/patrickschur/language-detection/blob/master/src/LanguageDetection/NgramParser.php#L137 

```
src/LanguageDetection/NgramParser.php:137 Type error: array_merge() expects at least 1 parameter, 0 given
```
When calling
```
LanguageDetection\Language->detect('\xF0\x9F\xA4\x97')
```

Would be great if the method detect() can return null or false if it can detect instead of a fatal !

Thank you for your awesome lib !

**Comment by patrickschur** [comment]
I didn't know that. Thanks! I will accept your pull request.

**Comment by arsonik** [comment]
👌🏻
