### ISSUE TITLE
Make location of the language resources configurable

### ISSUE THREAD

**Issue by pavolsenko** [patrickschur/language-detection#9]
It would be nice if the location of the resources would be configurable. Currently the `Trainer` and `Language` classes are bound to the `resources` folder. It would make managing the trainer files a bit easier. 

Thanks :)

**Comment by patrickschur** [comment]
That's a good idea. I'll see what I can do.
Thanks ;)

**Comment by patrickschur** [comment]
Sorry for the long time, you had to wait. I was a bit busy. 
But now I want to let you know I added an experimental support for custom directories. 
Please have a look. :)

**Comment by pavolsenko** [comment]
Looks good thanks :)
